### ISSUE TITLE
Cannot read property 'includes' of undefined when clicked on a deployment

### ISSUE THREAD

**Issue by ShubhamVerma1811** [frencojobs/vscode-vercel#4] opened 2021-01-31 07:47 UTC
I tried opening the deployment while vercel was building the project and ever since it doesn't open and this error pops up. 
On;y for this deployment.

![Screenshot (476)](https://user-images.githubusercontent.com/25576658/106377935-90444600-63c6-11eb-9af6-9ac976c0af19.png)

**Comment by frencojobs** [comment] 2021-01-31 10:04
Thanks for taking the time to open an issue. It was caused by a deployment that is not linked to a git commit. It will be fixed in v1.0.2.

**Closed** 2021-01-31 10:04 UTC
